name: product-catalog
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name : Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Product Catalog Service
        run: 
          cd src/product-catalog
          go mod download
          go build -o product-catalog-service main.go
      - name: Run Tests
        run: 
          go test ./src/product-catalog/... -v  -covprofile=coverage.out

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage.out 
  Code-Quality:
    runs-on: ubuntu-latest
    name: Code Quality Check
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run GolangCI-Lint
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run ./src/product-catalog/...

  Docker-Build-and-Deploy:
    needs: [build, Code-Quality]  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: install Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3   
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: src/product-catalog
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/product-catalog:${{ github.sha }}

  Update-to-Kubernetes:
    needs: Docker-Build-and-Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          token: ${{ secrets.GIT_TOKEN }}

      - name : update tag in k8s deployment file
        run: |
         sed -i 's|image: .*|image: '${{ secrets.DOCKER_USERNAME }}'/product-catalog:'"${{ github.sha }}"'|g' kubernetes/productcatalog/deploy.yaml 

      - name: Commit and Push changes
        run: |
          git config --global user.name 'padmaja92'
          git config --global user.email 'amaradhi.padmaja@gmail.com'
          git add kubernetes/productcatalog/deploy.yaml
          git commit -m "[CI]: Update product-catalog image tag to ${{ github.sha }}"
          git push  

